{"name": "发送一条新建的频道消息（应用6-应用已经被删除）", "status": "failed", "statusDetails": {"message": "AssertionError: 断言失败 -|- 实际结果:获取access_token失败，或者access_token无效 || 预期结果: 应用信息验证失败", "trace": "cls = <class 'tools.data_process.DataProcess'>\nresponse = {'errcode': '100003', 'errmsg': '获取access_token失败，或者access_token无效'}\nexpect_str = '{\"$.errmsg\":\"应用信息验证失败\"}'\n\n    @classmethod\n    def assert_result(cls, response: dict, expect_str: str):\n        \"\"\" 预期结果实际结果断言方法\n        :param response: 实际响应结果\n        :param expect_str: 预期响应内容，从excel中读取\n        return None\n        \"\"\"\n        # 后置sql变量转换\n        expect_str = rep_expr(expect_str, DataProcess.response_dict)\n        expect_dict = convert_json(expect_str)\n        index = 0\n        for k, v in expect_dict.items():\n            # 获取需要断言的实际结果部分\n            actual = extractor(response, k)\n            index += 1\n            logger.info(f'第{index}个断言,实际结果:{actual} | 预期结果:{v} \\n断言结果 {actual == v}')\n            allure_step(f'第{index}个断言',  f'实际结果:{actual} = 预期结果:{v}')\n            try:\n>               assert actual == v\nE               AssertionError\n\ntools/data_process.py:118: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\ncases = ['case_151', '消息中心应用消息', '发送消息', '发送一条新建的频道消息（应用6-应用已经被删除）', '/v1/message/send', '', ...]\n\n    @pytest.mark.flaky(reruns=0, reruns_delay=1)\n    def test_main(cases):#cases, get_db\n        # 此处的cases入参来自与 conftest.py  文件中 cases函数，与直接使用 @pytest.mark.parametrize\n        # 有着差不多的效果\n        # 发送请求\n        response, expect, sql = BaseRequest.send_request(cases)\n        # 执行sql\n        # DataProcess.handle_sql(sql, get_db)\n        # 断言操作\n>       DataProcess.assert_result(response, expect)\n\ntest/test_api.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ncls = <class 'tools.data_process.DataProcess'>\nresponse = {'errcode': '100003', 'errmsg': '获取access_token失败，或者access_token无效'}\nexpect_str = '{\"$.errmsg\":\"应用信息验证失败\"}'\n\n    @classmethod\n    def assert_result(cls, response: dict, expect_str: str):\n        \"\"\" 预期结果实际结果断言方法\n        :param response: 实际响应结果\n        :param expect_str: 预期响应内容，从excel中读取\n        return None\n        \"\"\"\n        # 后置sql变量转换\n        expect_str = rep_expr(expect_str, DataProcess.response_dict)\n        expect_dict = convert_json(expect_str)\n        index = 0\n        for k, v in expect_dict.items():\n            # 获取需要断言的实际结果部分\n            actual = extractor(response, k)\n            index += 1\n            logger.info(f'第{index}个断言,实际结果:{actual} | 预期结果:{v} \\n断言结果 {actual == v}')\n            allure_step(f'第{index}个断言',  f'实际结果:{actual} = 预期结果:{v}')\n            try:\n                assert actual == v\n            except AssertionError:\n>               raise AssertionError(f'断言失败 -|- 实际结果:{actual} || 预期结果: {v}')\nE               AssertionError: 断言失败 -|- 实际结果:获取access_token失败，或者access_token无效 || 预期结果: 应用信息验证失败\n\ntools/data_process.py:120: AssertionError"}, "steps": [{"name": "请求地址", "status": "passed", "attachments": [{"name": "请求地址", "source": "33d30975-0811-428e-8b5f-d84d6319bdf7-attachment.txt", "type": "text/plain"}], "start": 1622542451172, "stop": 1622542451172}, {"name": "请求头", "status": "passed", "attachments": [{"name": "请求头", "source": "689785b4-0b30-4950-b781-3f90f22a4e3f-attachment.txt", "type": "text/plain"}], "start": 1622542451172, "stop": 1622542451172}, {"name": "请求参数", "status": "passed", "attachments": [{"name": "请求参数", "source": "bdb119bf-b666-4718-89f4-266919272199-attachment.txt", "type": "text/plain"}], "start": 1622542451178, "stop": 1622542451178}, {"name": "上传文件", "status": "passed", "attachments": [{"name": "上传文件", "source": "c37881a3-d0c3-495c-a5d1-eadd5c89b560-attachment.txt", "type": "text/plain"}], "start": 1622542451178, "stop": 1622542451179}, {"name": "响应耗时(s)", "status": "passed", "attachments": [{"name": "响应耗时(s)", "source": "ef3b6130-2eac-4ec5-a764-c9d3d9b5d37a-attachment.txt", "type": "text/plain"}], "start": 1622542451280, "stop": 1622542451281}, {"name": "响应内容", "status": "passed", "attachments": [{"name": "响应内容", "source": "a3fa818d-5f0c-4cc4-8fd2-2316da3f0b24-attachment.txt", "type": "text/plain"}], "start": 1622542451281, "stop": 1622542451281}, {"name": "存储实际响应", "status": "passed", "attachments": [{"name": "存储实际响应", "source": "8a92863d-455a-405d-b938-0d99a28eacd0-attachment.txt", "type": "text/plain"}], "start": 1622542451282, "stop": 1622542451286}, {"name": "第1个断言", "status": "passed", "attachments": [{"name": "第1个断言", "source": "0257ee8f-55a3-42e3-a0a6-6c9b05d22238-attachment.txt", "type": "text/plain"}], "start": 1622542451287, "stop": 1622542451287}], "parameters": [{"name": "cases", "value": "['case_151', '消息中心应用消息', '发送消息', '发送一条新建的频道消息（应用6-应用已经被删除）', '/v1/message/send', '', 'post', 'json', '', '{\\n \"appid\": \"&$.test_023..datas[9].app_id&\",\\n \"access_token\": \"&$.case_100.access_token&\",\\n \"to_users\": [\"&$.test_010..datas[0].uid&\", \"&$.test_011..datas[0].uid&\", \"&$.test_004..datas[0].uid&\", \"&$.test_005..datas[0].uid&\"],\\n \"type\": \"text\",\\n \"message\": {\\n  \"content\": \"测试这个频道消息\"\\n },\\n \"msg_status\": \"1\"\\n}', '', '{\\n    \"errcode\": \"300002\",\\n    \"errmsg\": \"应用信息验证失败\"\\n}', '{\"$.errmsg\":\"应用信息验证失败\"}']"}], "start": 1622542451171, "stop": 1622542451287, "uuid": "b5e87300-b451-459c-8742-61578b176827", "historyId": "3700422daddb53d8d6739beb7ffeb61f", "testCaseId": "881516e7ef2e2aa5436f6a3c3e6a5bcb", "fullName": "test.test_api#test_main", "labels": [{"name": "tag", "value": "flaky(reruns=0, reruns_delay=1)"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "liuchengxudeMacBook-Pro.local"}, {"name": "thread", "value": "19614-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_api"}]}